[project]
name = "salmonrun-calendar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "fake-useragent>=2.0.3",
    "icalendar>=6.1.1",
    "requests>=2.32.3",
]
